#!/bin/sh

export PROJECT=DE10NanoTest
export PATH=$PATH:/opt/Altera/quartus/bin:/opt/Altera/quartus/sopc_builder/bin:

# --------------------------------------------------------------------------------------------------
rm -rf db incremental_db output_files
rm -rf ${PROJECT}.qpf ${PROJECT}.qsf ${PROJECT}.qws

# --------------------------------------------------------------------------------------------------
#qsys-generate HPS.qsys --synthesis=VERILOG --output-directory=HPS --family="Cyclone V" --part=5CSEBA6U23I7

# --------------------------------------------------------------------------------------------------
quartus_sh  -t ${PROJECT}.tcl ${PROJECT} .
quartus_map --read_settings_files=on  --write_settings_files=off $PROJECT -c $PROJECT
quartus_fit --read_settings_files=off --write_settings_files=off $PROJECT -c $PROJECT
quartus_asm --read_settings_files=off --write_settings_files=off $PROJECT -c $PROJECT
quartus_sta $PROJECT -c $PROJECT

# --------------------------------------------------------------------------------------------------
quartus_cpf -c -d EPCS64 -s 5CSEBA6 "./output_files/${PROJECT}.sof" "./output_files/${PROJECT}.jic"
quartus_pgm -c 1 -m jtag -o "p;./output_files/${PROJECT}.sof@2"
quartus_pgm -c 1 -m jtag -o "ipv;./output_files/${PROJECT}.jic;EPCS64@2"

